create table public.employee (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  first_name text null,
  last_name text null,
  email text null,
  contact text null,
  address text null,
  dob date null,
  birthday date null,
  gender text null,
  avatar_url text null,
  resume_url text null,
  introduction text null,
  status text null default 'Pending'::text,
  role text null default 'User'::text,
  email_notifications boolean null default true,
  timezone text null default 'UTC+8'::text,
  time_format text null default '12h'::text,
  theme_preference text null default 'light'::text,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  last_seen timestamp with time zone null default now(),
  modified_by_name text null,
  modified_at timestamp with time zone null,
  department_name text null,
  work_location text null,
  constraint employee_pkey primary key (id),
  constraint employee_user_id_key unique (user_id)
) TABLESPACE pg_default;